jobs: 

- job: 'android_arm_debug'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - powershell: |
          $temp = "$(ANDROID_NDK_PATH)"
          echo "##vso[task.setvariable variable=android_ndk;isOutput=true]$temp"
    name: ConvertNDKPath
  - script: echo $(ConvertNDKPath.android_ndk)
    name: echovar
  #- script: cinst ninja
  #-replace '\\','/'

  #- task: CMake@1
   # inputs: 
    #  cmakeArgs: .. -G Ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK="$(ANDROID_NDK_PATH)"
    #displayName: 'Generate Solution'

 # - task: CMake@1
  #  inputs: 
   #   cmakeArgs: --build . -j 4 --config Debug
   # displayName: 'Build'
