jobs: 
- job: 'win_x86_debug'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1 -DCMAKE_GENERATOR_PLATFORM=Win32
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Debug
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'win_x86_release'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1 -DCMAKE_GENERATOR_PLATFORM=Win32
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Release
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'win_x64_debug'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1 -DCMAKE_GENERATOR_PLATFORM=x64
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Debug
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'win_x64_release'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1 -DCMAKE_GENERATOR_PLATFORM=x64
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Release
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'win_arm_debug'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DCMAKE_GENERATOR_PLATFORM=ARM
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Debug
    displayName: 'Build'

- job: 'win_arm_release'
  pool: 
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DCMAKE_GENERATOR_PLATFORM=ARM
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Release
    displayName: 'Build'

- job: 'mac_x64_debug'
  pool: 
    vmImage: 'macOS-10.13'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Debug
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'mac_x64_release'
  pool: 
    vmImage: 'macOS-10.13'
  steps:
  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Release
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'linux_x64_debug'
  pool: 
    vmImage: 'Ubuntu-16.04'
  steps:
  # Remove the install of CMake 3.12 once hosted image is updated from 3.10
  - script: |
      curl -sL https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh -o cmakeinstall.sh
      chmod +x cmakeinstall.sh
      sudo ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir
      rm cmakeinstall.sh
    displayName: 'Install CMake 3.12 on Linux'

  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Debug
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'

- job: 'linux_x64_release'
  pool: 
    vmImage: 'Ubuntu-16.04'
  steps:
  # Remove the install of CMake 3.12 once hosted image is updated from 3.10
  - script: |
      curl -sL https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh -o cmakeinstall.sh
      chmod +x cmakeinstall.sh
      sudo ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir
      rm cmakeinstall.sh
    displayName: 'Install CMake 3.12 on Linux'

  - task: CMake@1
    inputs: 
      cmakeArgs: .. -DBUILD_TESTING=1
    displayName: 'Generate Solution'

  - task: CMake@1
    inputs: 
      cmakeArgs: --build . -j 4 --config Release
    displayName: 'Build'

  - script: |
      cd build
      ctest -j 4
    displayName: 'Test'
