name: Opus Build Matrix

on: [push, pull_request]

jobs:
  CMake:
    name: CMake as submodule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: QEMU
        run: ls -1 /proc/sys/fs/binfmt_misc | grep qemu