on:
- push
- pull_request
jobs:
  win-x86_64:
    name: win-x86_64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: mkdir build
      name: Create Work Dir
    - working-directory: build
      run: cmake .. -DOPUS_BUILD_PROGRAMS=ON -DOPUS_BUILD_TESTING=ON -DOPUS_DISABLE_INTRINSICS=ON
        -DOPUS_FIXED_POINT=ON -G "Visual Studio 16 2019" -A x64
      name: Configure
    - working-directory: build
      run: cmake --build . --config Release
      name: Build
    - working-directory: build
      run: ctest
      name: Test
name: Opus Build Matrix