jobs:
  Something:
    name: Test build with CMake 3.1.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create Work Dir
      run: mkdir build
    - name: Configure
      run: cmake .. -DOPUS_BUILD_PROGRAMS=ON -#DBUILD_TESTING=ON
      working-directory: ./build
    - name: Build
      run: make -j 2 -s
      working-directory: ./build
    - name: Test
      run: ctest -j 2
      working-directory: ./build
name: Opus Build Matrix
'true':
- push
- pull_request